[tool.poetry]
name = "nocturne-worker"
version = "0.1.0"
description = "Worker para procesamiento de suscripciones"
authors = ["mzkchris"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "1.35.0"
aws-lambda-powertools = "3.4.1"
python-dotenv = "1.0.1"

[tool.poetry.group.dev.dependencies]
awscli-local = "0.22.0"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
