name: CI Validation

on:
  push:
    branches:
      - develop
      - 'feature/*'  # <--- Esto activa el CI en tus ramas de trabajo
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    # --- ESTO ES LO QUE SOLUCIONA EL ERROR ---para mocks tests
    env:
      AWS_ACCESS_KEY_ID: testing
      AWS_SECRET_ACCESS_KEY: testing
      AWS_SECURITY_TOKEN: testing
      AWS_SESSION_TOKEN: testing
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1
    # -----------------------------------------
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Lint with Black
        run: poetry run black --check .

      - name: Run Tests
        run: poetry run pytest
